# **Project Title**
Comprehensive Analysis of Fragrances in the E-Commerce Market

# **Domain**

E-commerce Market

# **Objective**

1. To identify meaningful patterns, trends, and insights from the dataset using exploratory data analysis (EDA)

2. To clean, transform, and preprocess the data for analysis

3. To create meaningful visualizations that clearly explain the story behind the data

4. To provide actionable insights and recommendations from the analysis

# **Outcome**

The project helps uncover key patterns, trends, and hidden insights from the dataset. The analysis provides a clear understanding of the data and supports decision-making with evidence-based findings.

# **Dataset Information**

**Source:** https://www.kaggle.com/datasets/kanchana1990/perfume-e-commerce-dataset-2024?resource=download

**Year / Timeline:** Data collected during 2024

**Dataset Description:**
The Perfume E-Commerce Dataset 2024 comprises detailed information on 2000 perfume listings sourced from eBay, split into two separate CSV files for men's and women's perfumes, each containing 1000 entries. This dataset provides a

comprehensive view of the current market trends, pricing, availability, and geographical distribution of perfumes in the e-commerce space.

**Column description**


*   **Brand:** The brand of the perfume.

*   **Title:** The title of the listing.

*   **Type:** The type of perfume (e.g., Eau de Parfum, Eau de Toilette).

*   **Price:** The price of the perfume.
*   **PriceWithCurrency:** The price with currency notation.


*   **Available:** The number of items available


*   **AvailableText:** Text description of availability.


*   **Sold:** The number of items sold.

*   **LastUpdated:** The last updated timestamp of the listing.
*   **ItemLocation:** The location of the item.

# **Type of Analysis**

**1. Descriptive Analysis (Summarizing the Dataset)**

This level summarizes the "what" of the data based on $2,000$ total listings






($1,000$ Men's, $1,000$ Women's).



*   Pricing: Men's perfumes are generally more expensive, with an average price of $\$46.48$ compared to $\$39.89$ for Women's.
*  Sales Volume: The Men's category shows significantly higher total sales activity on eBay ($761,669$ units sold) compared to the Women's category ($489,364$ units sold).


*   Market Share: Calvin Klein and Versace are the high-volume leaders across both datasets, accounting for over $270,000$ units sold combined.
*  Product Types: The inventory is primarily split between Eau de Parfum (EDP) and Eau de Toilette (EDT), with EDPs commanding a higher price premium.


**2. Diagnostic Analysis (Finding Reasons Behind Patterns)**

This level investigates "why" certain trends exist in the marketplace.


*   Concentration vs. Price: Eau de Parfum listings have an average price of $\$49.45$, which is roughly $30\%$ higher than Eau de Toilette ($\$38.13$). This confirms that consumers/sellers value the higher oil concentration and longevity of EDPs.

*   The "Mass-Appeal" Brand Effect: Brands like Calvin Klein and Davidoff have lower-than-average prices (approx. $\$24.50$) which directly correlates with their massive sales volume. Their strategy on eBay appears to be "high volume, low margin."
*   Gender Sales Gap: The higher sales volume in Men’s perfumes despite higher average prices suggests a more "utilitarian" or "repeat-purchase" behavior in the men’s segment on eBay, or a higher concentration of popular "blue" fragrances that sell in bulk.


**3. Predictive Analysis (Forecasting Trends)**
Using basic statistical modeling (Linear Regression) to forecast outcomes.


*   Sales vs. Price Forecast: Based on current trends, if a perfume's price is increased from $\$30$ to $\$50$, the predicted sales volume per listing drops from approximately $83$ units to $65$ units.

*   Inventory Outcome: Listings for "Unknown" or "Other" fragrance types are predicted to have lower turnover rates, as they carry the highest average price ($\$58.52$) but lack the categorical clarity buyers search for.
*   Brand Growth: Given its high listing count ($53$) and high sales ($128,000+$), Versace is predicted to remain the most stable "premium-midrange" brand for consistent revenue.

**4. Prescriptive Analysis (Recommendations for Business Decisions)**
Strategic actions based on the data findings.


*   Stocking Strategy: Prioritize sourcing Calvin Klein and Davidoff for quick inventory turnover. While the margins are lower (avg. price $\approx \$24$), the volume is unmatched.

*   Pricing Sweet Spot: For maximum sales velocity, sellers should aim for a price point between $\$25$ and $\$35$. Listings in this range capture the highest volume of buyers.
*   Listing Optimization: Always specify the Type (EDP/EDT). "Unknown" types are priced higher on average but likely face more resistance; labeling a fragrance correctly as "Eau de Toilette" can make it appear more competitively priced against the market average.


*   Expansion Opportunity: Focus on Men's Gift Sets or 3.4oz Sprays, as the Men's category is currently moving nearly $55\%$ more volume than the Women's category on this platform.

# Stages for DA Project

## Stage 1 – Problem Definition and Dataset Selection

Define the business problem and expected outcome

Choose dataset and explain its source, size, and features

Import libraries, load dataset

Dataset description (rows, columns, features)

Initial EDA (head, info, describe, shape, null checks, duplicate check)

In [2]:
import pandas as pd
import numpy as np

In [3]:
df1 = pd.read_csv('https://raw.githubusercontent.com/Meganathan1294/Main-project-/refs/heads/main/ebay_mens_perfume.csv')
df2 = pd.read_csv('https://raw.githubusercontent.com/Meganathan1294/Main-project-/refs/heads/main/ebay_womens_perfume.csv')
df1.head()
df2.head()

,brand,title,type,price,priceWithCurrency,available,availableText,sold,lastUpdated,itemLocation
0,Carolina Herrera,Good Girl by Carolina Herrera 2.7 oz Eau De Pa...,Eau de Parfum,43.99,US $43.99/ea,2.0,2 available / 393 sold,393.0,"May 23, 2024 10:43:50 PDT","Thomasville, Alabama, United States"
1,As Shown,Parfums de Marly Delina La Rosee Eau de Parfum...,Eau de Parfum,79.99,US $79.99,5.0,5 available / 40 sold,40.0,"May 24, 2024 00:15:48 PDT","New Jersey, Hong Kong"
2,PRADA,PRADA Paradoxe by Prada EDP 3.0oz/90ml Spray P...,Eau de Parfum,59.99,US $59.99,10.0,More than 10 available / 35 sold,35.0,"May 14, 2024 20:54:25 PDT","Orange, New Jersey, United States"
3,As Show,J'adore Parfum D'eau by Christian 3.4 oz EDP F...,Eau de Parfum,59.99,US $59.99/ea,10.0,More than 10 available / 9 sold,9.0,"May 23, 2024 01:23:05 PDT","USA, New Jersey, Hong Kong"
4,Khadlaj,Shiyaaka for Men EDP Spray 100ML (3.4 FL.OZ) B...,Eau de Parfum,29.99,US $29.99/ea,10.0,More than 10 available,NaN,NaN,"Little Ferry, New Jersey, United States"

In [4]:
print(df1.shape)
df2.shape

(1000, 10)

(1000, 10)

In [5]:
print (df1.info())
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   brand              999 non-null    object
 1   title              1000 non-null   object
 2   type               997 non-null    object
 3   price              1000 non-null   float64
 4   priceWithCurrency  1000 non-null   object
 5   available          889 non-null    float64
 6   availableText      997 non-null    object
 7   sold               994 non-null    float64
 8   lastUpdated        947 non-null    object
 9   itemLocation       1000 non-null   object
dtypes: float64(3), object(7)
memory usage: 78.3+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   brand              999 non-null    object
 1   title              1000 non-null   object
 2   type               998 non-null    object
 3   price              1000 non-null   float64
 4   priceWithCurrency  1000 non-null   object
 5   available          869 non-null    float64
 6   availableText      992 non-null    object
 7   sold               984 non-null    float64
 8   lastUpdated        927 non-null    object
 9   itemLocation       1000 non-null   object
dtypes: float64(3), object(7)
memory usage: 78.3+ KB

In [6]:
print(df1.head())
df2.head()

            brand                                              title  \
0            Dior  Christian Dior Sauvage Men's EDP 3.4 oz Fragra...
1         AS SHOW  A-v-entus Eau de Parfum 3.3 oz 100ML Millesime...
2       Unbranded                   HOGO BOSS cologne For Men 3.4 oz
3  Giorgio Armani  Acqua Di Gio by Giorgio Armani 6.7 Fl oz Eau D...
4         Lattafa  Lattafa Men's Hayaati Al Maleky EDP Spray 3.4 ...

              type   price priceWithCurrency  available  \
0    Eau de Parfum   84.99      US $84.99/ea       10.0
1    Eau de Parfum  109.99        US $109.99        8.0
2  Eau de Toilette  100.00        US $100.00       10.0
3  Eau de Toilette   44.99      US $44.99/ea        2.0
4       Fragrances   16.91         US $16.91        NaN

                           availableText   sold                lastUpdated  \
0      More than 10 available / 116 sold  116.0  May 24, 2024 10:03:04 PDT
1                  8 available / 48 sold   48.0  May 23, 2024 23:07:49 PDT
2       More than 10 available / 27 sold   27.0  May 22, 2024 21:55:43 PDT
3                 2 available / 159 sold  159.0  May 24, 2024 03:30:43 PDT
4  Limited quantity available / 156 sold  156.0  May 24, 2024 07:56:25 PDT

                             itemLocation
0     Allen Park, Michigan, United States
1                Atlanta, Georgia, Canada
2       Dearborn, Michigan, United States
3  Reinholds, Pennsylvania, United States
4       Brooklyn, New York, United States

,brand,title,type,price,priceWithCurrency,available,availableText,sold,lastUpdated,itemLocation
0,Carolina Herrera,Good Girl by Carolina Herrera 2.7 oz Eau De Pa...,Eau de Parfum,43.99,US $43.99/ea,2.0,2 available / 393 sold,393.0,"May 23, 2024 10:43:50 PDT","Thomasville, Alabama, United States"
1,As Shown,Parfums de Marly Delina La Rosee Eau de Parfum...,Eau de Parfum,79.99,US $79.99,5.0,5 available / 40 sold,40.0,"May 24, 2024 00:15:48 PDT","New Jersey, Hong Kong"
2,PRADA,PRADA Paradoxe by Prada EDP 3.0oz/90ml Spray P...,Eau de Parfum,59.99,US $59.99,10.0,More than 10 available / 35 sold,35.0,"May 14, 2024 20:54:25 PDT","Orange, New Jersey, United States"
3,As Show,J'adore Parfum D'eau by Christian 3.4 oz EDP F...,Eau de Parfum,59.99,US $59.99/ea,10.0,More than 10 available / 9 sold,9.0,"May 23, 2024 01:23:05 PDT","USA, New Jersey, Hong Kong"
4,Khadlaj,Shiyaaka for Men EDP Spray 100ML (3.4 FL.OZ) B...,Eau de Parfum,29.99,US $29.99/ea,10.0,More than 10 available,NaN,NaN,"Little Ferry, New Jersey, United States"

In [7]:
print(df1.tail())
df2.tail()

            brand                                              title  \
995         GUESS  Guess 1981 by Guess cologne for men EDT 3.3 / ...
996         Armaf  Club de Nuit Intense by Armaf cologne for men ...
997  Paco Rabanne  Invictus by Paco Rabanne for Men EDT Spray 3.4...
998        Lomani  Lomani EDT Cologne 3.4 oz Men - Authentic, Bra...
999  Estee Lauder  Beyond Paradise by Estee Lauder for Men Cologn...

                type  price priceWithCurrency  available  \
995  Eau de Toilette  20.28      US $20.28/ea       45.0
996  Eau de Toilette  30.58         US $30.58       10.0
997  Eau de Toilette  39.99      US $39.99/ea        2.0
998  Eau de Toilette   9.99       US $9.99/ea        2.0
999    Cologne spray  17.49      US $17.49/ea       10.0

                        availableText    sold                lastUpdated  \
995         45 available / 1,613 sold  1613.0  May 24, 2024 08:14:07 PDT
996  More than 10 available / 31 sold    31.0  May 23, 2024 08:39:30 PDT
997            2 available / 305 sold   305.0  May 23, 2024 15:27:18 PDT
998             2 available / 22 sold    22.0  May 20, 2024 13:20:54 PDT
999  More than 10 available / 24 sold    24.0  Feb 28, 2024 07:27:01 PST

                              itemLocation
995           Dallas, Texas, United States
996                          United States
997       Jamaica, New York, United States
998  Lincoln Park, Michigan, United States
999     Keyport, New Jersey, United States

,brand,title,type,price,priceWithCurrency,available,availableText,sold,lastUpdated,itemLocation
995,Avon,Avon Far Away Infinity Eau de Parfum 1.7 fl. o...,Eau de Parfum,13.89,US $13.89,10.0,More than 10 available / 157 sold,157.0,"May 16, 2024 22:35:29 PDT","West Palm Beach, Florida, United States"
996,Mancera,Roses Greedy by Mancera perfume for unisex EDP...,Eau de Parfum,57.85,US $57.85/ea,33.0,33 available / 58 sold,58.0,"May 24, 2024 08:03:11 PDT","Dallas, Texas, United States"
997,Unbranded,"Sweet Tooth Eau de Parfum, Perfume for Women, ...",1,30.96,US $30.96,2.0,2 available / 3 sold,3.0,"May 17, 2024 23:16:41 PDT","New York, New York, United States"
998,Juliette Has A Gun,MMMM BY Juliette Has A Gun perfume for her EDP...,Eau de Perfume,53.99,US $53.99/ea,3.0,3 available / 117 sold,117.0,"May 13, 2024 22:19:34 PDT","Dallas, Texas, United States"
999,Paris Hilton,PARIS HILTON ELECTRIFY for Women Cologne 3.4 o...,Eau de Parfum,14.99,US $14.99/ea,4.0,4 available / 51 sold,51.0,"May 22, 2024 05:44:45 PDT","TX, United States"

In [8]:
print (df1.describe())
df2.describe()

             price   available          sold
count  1000.000000  889.000000    994.000000
mean     46.481200   20.046119    766.266600
std      35.527862   61.547985   3200.971733
min       3.000000    2.000000      1.000000
25%      22.990000    5.000000     14.000000
50%      35.710000   10.000000     49.500000
75%      59.000000   10.000000    320.500000
max     259.090000  842.000000  54052.000000

             price   available          sold
count  1000.000000  869.000000    984.000000
mean     39.892980   21.426928    497.321138
std      29.072186   51.476703   1372.510561
min       1.990000    2.000000      1.000000
25%      20.700000    6.000000     15.000000
50%      32.990000   10.000000     52.000000
75%      49.990000   10.000000    263.750000
max     299.990000  557.000000  17854.000000

In [9]:
print(df1.isnull().sum())
df2.isnull().sum()

brand                  1
title                  0
type                   3
price                  0
priceWithCurrency      0
available            111
availableText          3
sold                   6
lastUpdated           53
itemLocation           0
dtype: int64

brand                  1
title                  0
type                   2
price                  0
priceWithCurrency      0
available            131
availableText          8
sold                  16
lastUpdated           73
itemLocation           0
dtype: int64

In [10]:
print (df1.size)
df2.size

10000

10000

In [ ]:
print(df1.columns)
df2.columns

Index(['brand', 'title', 'type', 'price', 'priceWithCurrency', 'available',
       'availableText', 'sold', 'lastUpdated', 'itemLocation'],
      dtype='object')

Index(['brand', 'title', 'type', 'price', 'priceWithCurrency', 'available',
       'availableText', 'sold', 'lastUpdated', 'itemLocation'],
      dtype='object')

In [11]:
print(df1.dtypes)
df2.dtypes

brand                 object
title                 object
type                  object
price                float64
priceWithCurrency     object
available            float64
availableText         object
sold                 float64
lastUpdated           object
itemLocation          object
dtype: object

brand                 object
title                 object
type                  object
price                float64
priceWithCurrency     object
available            float64
availableText         object
sold                 float64
lastUpdated           object
itemLocation          object
dtype: object

In [12]:
print(df1.duplicated().sum())
df2.duplicated().sum()

0

np.int64(1)

In [13]:
print(df1.isna().sum())
df2.isna().sum()

brand                  1
title                  0
type                   3
price                  0
priceWithCurrency      0
available            111
availableText          3
sold                   6
lastUpdated           53
itemLocation           0
dtype: int64

brand                  1
title                  0
type                   2
price                  0
priceWithCurrency      0
available            131
availableText          8
sold                  16
lastUpdated           73
itemLocation           0
dtype: int64

## Stage 2 – Data Cleaning and Pre-processing

Handle missing values (impute or drop)

Handle duplicates

Treat outliers if required

Check skewness and apply transformations

Convert data types if needed

Feature transformations (date parts, derived fields if required for analysis)

In [14]:
import pandas as pd
import numpy as np

In [15]:
# Add gender labels and combine
df1['gender'] = 'Men'
df2['gender'] = 'Women'
df = pd.concat([df1, df2], ignore_index=True)
df

,brand,title,type,price,priceWithCurrency,available,availableText,sold,lastUpdated,itemLocation,gender
0,Dior,Christian Dior Sauvage Men's EDP 3.4 oz Fragra...,Eau de Parfum,84.99,US $84.99/ea,10.0,More than 10 available / 116 sold,116.0,"May 24, 2024 10:03:04 PDT","Allen Park, Michigan, United States",Men
1,AS SHOW,A-v-entus Eau de Parfum 3.3 oz 100ML Millesime...,Eau de Parfum,109.99,US $109.99,8.0,8 available / 48 sold,48.0,"May 23, 2024 23:07:49 PDT","Atlanta, Georgia, Canada",Men
2,Unbranded,HOGO BOSS cologne For Men 3.4 oz,Eau de Toilette,100.00,US $100.00,10.0,More than 10 available / 27 sold,27.0,"May 22, 2024 21:55:43 PDT","Dearborn, Michigan, United States",Men
3,Giorgio Armani,Acqua Di Gio by Giorgio Armani 6.7 Fl oz Eau D...,Eau de Toilette,44.99,US $44.99/ea,2.0,2 available / 159 sold,159.0,"May 24, 2024 03:30:43 PDT","Reinholds, Pennsylvania, United States",Men
4,Lattafa,Lattafa Men's Hayaati Al Maleky EDP Spray 3.4 ...,Fragrances,16.91,US $16.91,NaN,Limited quantity available / 156 sold,156.0,"May 24, 2024 07:56:25 PDT","Brooklyn, New York, United States",Men
...,...,...,...,...,...,...,...,...,...,...,...
1995,Avon,Avon Far Away Infinity Eau de Parfum 1.7 fl. o...,Eau de Parfum,13.89,US $13.89,10.0,More than 10 available / 157 sold,157.0,"May 16, 2024 22:35:29 PDT","West Palm Beach, Florida, United States",Women
1996,Mancera,Roses Greedy by Mancera perfume for unisex EDP...,Eau de Parfum,57.85,US $57.85/ea,33.0,33 available / 58 sold,58.0,"May 24, 2024 08:03:11 PDT","Dallas, Texas, United States",Women
1997,Unbranded,"Sweet Tooth Eau de Parfum, Perfume for Women, ...",1,30.96,US $30.96,2.0,2 available / 3 sold,3.0,"May 17, 2024 23:16:41 PDT","New York, New York, United States",Women
1998,Juliette Has A Gun,MMMM BY Juliette Has A Gun perfume for her EDP...,Eau de Perfume,53.99,US $53.99/ea,3.0,3 available / 117 sold,117.0,"May 13, 2024 22:19:34 PDT","Dallas, Texas, United States",Women
1999,Paris Hilton,PARIS HILTON ELECTRIFY for Women Cologne 3.4 o...,Eau de Parfum,14.99,US $14.99/ea,4.0,4 available / 51 sold,51.0,"May 22, 2024 05:44:45 PDT","TX, United States",Women

In [16]:
# Handle Missing Values
# Fill missing 'brand' with 'Unknown'
df['brand'] = df['brand'].fillna('Unknown')
df

,brand,title,type,price,priceWithCurrency,available,availableText,sold,lastUpdated,itemLocation,gender
0,Dior,Christian Dior Sauvage Men's EDP 3.4 oz Fragra...,Eau de Parfum,84.99,US $84.99/ea,10.0,More than 10 available / 116 sold,116.0,"May 24, 2024 10:03:04 PDT","Allen Park, Michigan, United States",Men
1,AS SHOW,A-v-entus Eau de Parfum 3.3 oz 100ML Millesime...,Eau de Parfum,109.99,US $109.99,8.0,8 available / 48 sold,48.0,"May 23, 2024 23:07:49 PDT","Atlanta, Georgia, Canada",Men
2,Unbranded,HOGO BOSS cologne For Men 3.4 oz,Eau de Toilette,100.00,US $100.00,10.0,More than 10 available / 27 sold,27.0,"May 22, 2024 21:55:43 PDT","Dearborn, Michigan, United States",Men
3,Giorgio Armani,Acqua Di Gio by Giorgio Armani 6.7 Fl oz Eau D...,Eau de Toilette,44.99,US $44.99/ea,2.0,2 available / 159 sold,159.0,"May 24, 2024 03:30:43 PDT","Reinholds, Pennsylvania, United States",Men
4,Lattafa,Lattafa Men's Hayaati Al Maleky EDP Spray 3.4 ...,Fragrances,16.91,US $16.91,NaN,Limited quantity available / 156 sold,156.0,"May 24, 2024 07:56:25 PDT","Brooklyn, New York, United States",Men
...,...,...,...,...,...,...,...,...,...,...,...
1995,Avon,Avon Far Away Infinity Eau de Parfum 1.7 fl. o...,Eau de Parfum,13.89,US $13.89,10.0,More than 10 available / 157 sold,157.0,"May 16, 2024 22:35:29 PDT","West Palm Beach, Florida, United States",Women
1996,Mancera,Roses Greedy by Mancera perfume for unisex EDP...,Eau de Parfum,57.85,US $57.85/ea,33.0,33 available / 58 sold,58.0,"May 24, 2024 08:03:11 PDT","Dallas, Texas, United States",Women
1997,Unbranded,"Sweet Tooth Eau de Parfum, Perfume for Women, ...",1,30.96,US $30.96,2.0,2 available / 3 sold,3.0,"May 17, 2024 23:16:41 PDT","New York, New York, United States",Women
1998,Juliette Has A Gun,MMMM BY Juliette Has A Gun perfume for her EDP...,Eau de Perfume,53.99,US $53.99/ea,3.0,3 available / 117 sold,117.0,"May 13, 2024 22:19:34 PDT","Dallas, Texas, United States",Women
1999,Paris Hilton,PARIS HILTON ELECTRIFY for Women Cologne 3.4 o...,Eau de Parfum,14.99,US $14.99/ea,4.0,4 available / 51 sold,51.0,"May 22, 2024 05:44:45 PDT","TX, United States",Women

In [17]:
# Fill missing 'available' and 'sold' with 0 (assuming no activity)
df['available'] = df['available'].fillna(0)
df['sold'] = df['sold'].fillna(0)
df

,brand,title,type,price,priceWithCurrency,available,availableText,sold,lastUpdated,itemLocation,gender
0,Dior,Christian Dior Sauvage Men's EDP 3.4 oz Fragra...,Eau de Parfum,84.99,US $84.99/ea,10.0,More than 10 available / 116 sold,116.0,"May 24, 2024 10:03:04 PDT","Allen Park, Michigan, United States",Men
1,AS SHOW,A-v-entus Eau de Parfum 3.3 oz 100ML Millesime...,Eau de Parfum,109.99,US $109.99,8.0,8 available / 48 sold,48.0,"May 23, 2024 23:07:49 PDT","Atlanta, Georgia, Canada",Men
2,Unbranded,HOGO BOSS cologne For Men 3.4 oz,Eau de Toilette,100.00,US $100.00,10.0,More than 10 available / 27 sold,27.0,"May 22, 2024 21:55:43 PDT","Dearborn, Michigan, United States",Men
3,Giorgio Armani,Acqua Di Gio by Giorgio Armani 6.7 Fl oz Eau D...,Eau de Toilette,44.99,US $44.99/ea,2.0,2 available / 159 sold,159.0,"May 24, 2024 03:30:43 PDT","Reinholds, Pennsylvania, United States",Men
4,Lattafa,Lattafa Men's Hayaati Al Maleky EDP Spray 3.4 ...,Fragrances,16.91,US $16.91,0.0,Limited quantity available / 156 sold,156.0,"May 24, 2024 07:56:25 PDT","Brooklyn, New York, United States",Men
...,...,...,...,...,...,...,...,...,...,...,...
1995,Avon,Avon Far Away Infinity Eau de Parfum 1.7 fl. o...,Eau de Parfum,13.89,US $13.89,10.0,More than 10 available / 157 sold,157.0,"May 16, 2024 22:35:29 PDT","West Palm Beach, Florida, United States",Women
1996,Mancera,Roses Greedy by Mancera perfume for unisex EDP...,Eau de Parfum,57.85,US $57.85/ea,33.0,33 available / 58 sold,58.0,"May 24, 2024 08:03:11 PDT","Dallas, Texas, United States",Women
1997,Unbranded,"Sweet Tooth Eau de Parfum, Perfume for Women, ...",1,30.96,US $30.96,2.0,2 available / 3 sold,3.0,"May 17, 2024 23:16:41 PDT","New York, New York, United States",Women
1998,Juliette Has A Gun,MMMM BY Juliette Has A Gun perfume for her EDP...,Eau de Perfume,53.99,US $53.99/ea,3.0,3 available / 117 sold,117.0,"May 13, 2024 22:19:34 PDT","Dallas, Texas, United States",Women
1999,Paris Hilton,PARIS HILTON ELECTRIFY for Women Cologne 3.4 o...,Eau de Parfum,14.99,US $14.99/ea,4.0,4 available / 51 sold,51.0,"May 22, 2024 05:44:45 PDT","TX, United States",Women

In [18]:
# Drop rows where 'type' is missing as it's crucial for our analysis
df.dropna(subset=['type'], inplace=True)

In [19]:
print("Missing values after cleaning:")
print(df.isnull().sum())

Missing values after cleaning:
brand                  0
title                  0
type                   0
price                  0
priceWithCurrency      0
available              0
availableText         11
sold                   0
lastUpdated          126
itemLocation           0
gender                 0
dtype: int64

In [20]:
# Remove Duplicates
df.drop_duplicates(inplace=True)

# Treat Outliers in Price using the IQR method
Q1 = df['price'].quantile(0.25)
Q3 = df['price'].quantile(0.75)
IQR = Q3 - Q1
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

In [21]:
# Filtering the outliers
df = df[(df['price'] >= lower_bound) & (df['price'] <= upper_bound)]

print(f"Dataset shape after removing outliers: {df.shape}")

Dataset shape after removing outliers: (1905, 11)

In [22]:
# Convert 'lastUpdated' to datetime
# Note: errors='coerce' will turn unparseable dates into NaT (Not a Time)
df['lastUpdated'] = pd.to_datetime(df['lastUpdated'], errors='coerce')

/tmp/ipykernel_1586/1183584822.py:3: FutureWarning: Parsed string "May 24, 2024 10:03:04 PDT" included an un-recognized timezone "PDT". Dropping unrecognized timezones is deprecated; in a future version this will raise. Instead pass the string without the timezone, then use .tz_localize to convert to a recognized timezone.
  df['lastUpdated'] = pd.to_datetime(df['lastUpdated'], errors='coerce')
/tmp/ipykernel_1586/1183584822.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['lastUpdated'] = pd.to_datetime(df['lastUpdated'], errors='coerce')

In [23]:
# Extract Year and Month as new features
df['update_month'] = df['lastUpdated'].dt.month
df['update_year'] = df['lastUpdated'].dt.year

/tmp/ipykernel_1586/4173271022.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['update_month'] = df['lastUpdated'].dt.month
/tmp/ipykernel_1586/4173271022.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['update_year'] = df['lastUpdated'].dt.year

In [24]:
# Clean the 'type' column (standardizing common names)
df['type'] = df['type'].str.strip()
df['type'] = df['type'].replace({'Eau de Perfume': 'Eau de Parfum', 'EDP': 'Eau de Parfum', 'EDT': 'Eau de Toilette'})

/tmp/ipykernel_1586/362217052.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['type'] = df['type'].str.strip()
/tmp/ipykernel_1586/362217052.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['type'] = df['type'].replace({'Eau de Perfume': 'Eau de Parfum', 'EDP': 'Eau de Parfum', 'EDT': 'Eau de Toilette'})

In [25]:
# 1. Remove the 'lastUpdated' and 'update_month' columns
df.drop(columns=['lastUpdated', 'update_month'], inplace=True, errors='ignore')

/tmp/ipykernel_1586/2798726208.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(columns=['lastUpdated', 'update_month'], inplace=True, errors='ignore')

In [26]:
# 2. Set all values in 'update_year' to 2024
df['update_year'] = 2024

/tmp/ipykernel_1586/3215817623.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['update_year'] = 2024

In [27]:
# 3. Save the updated version to your CSV
df.to_csv('cleaned_fragrance_data.csv', index=False)

In [28]:
# 4. Display the first few rows to verify
print("Columns removed and year updated to 2024.")
df.head()

Columns removed and year updated to 2024.

,brand,title,type,price,priceWithCurrency,available,availableText,sold,itemLocation,gender,update_year
0,Dior,Christian Dior Sauvage Men's EDP 3.4 oz Fragra...,Eau de Parfum,84.99,US $84.99/ea,10.0,More than 10 available / 116 sold,116.0,"Allen Park, Michigan, United States",Men,2024
2,Unbranded,HOGO BOSS cologne For Men 3.4 oz,Eau de Toilette,100.00,US $100.00,10.0,More than 10 available / 27 sold,27.0,"Dearborn, Michigan, United States",Men,2024
3,Giorgio Armani,Acqua Di Gio by Giorgio Armani 6.7 Fl oz Eau D...,Eau de Toilette,44.99,US $44.99/ea,2.0,2 available / 159 sold,159.0,"Reinholds, Pennsylvania, United States",Men,2024
4,Lattafa,Lattafa Men's Hayaati Al Maleky EDP Spray 3.4 ...,Fragrances,16.91,US $16.91,0.0,Limited quantity available / 156 sold,156.0,"Brooklyn, New York, United States",Men,2024
5,Multiple Brands,Men's Perfume Sampler 10pcs Sample Vials Desig...,Perfume,14.99,US $14.99,10.0,More than 10 available / 79 sold,79.0,"Houston, Texas, United States",Men,2024

## Stage 3 – EDA and Visualizations

Univariate Analysis → distribution of single variables (countplot, histogram, boxplot)

Bivariate Analysis → relation between two variables (scatterplot, barplot, correlation heatmap)

Multivariate Analysis → relation among 3+ variables (pairplot, grouped analysis, pivot tables, advanced plots)

Interpretation MUST with every visualization

Focus on business story not just charts

Each chart must be in seperate cells.

In [ ]:
# your chart here
# If you want more cells, you can add or less cells you can remove, but dont change the structure.

## Interpretation of your above chart

Explain the Chart.

What is it saying?

What features you used?

From this what you are showing us?

In [ ]:
# your code here
# If you want more cells, you can add or less cells you can remove, but dont change the structure.

## Interpretation of your above chart

Explain the Chart.

What is it saying?

What features you used?

From this what you are showing us?

In [ ]:
# your code here
# If you want more cells, you can add or less cells you can remove, but dont change the structure.

## Interpretation of your above chart

Explain the Chart.

What is it saying?

What features you used?

From this what you are showing us?

In [ ]:
# your code here
# If you want more cells, you can add or less cells you can remove, but dont change the structure.

## Interpretation of your above chart

Explain the Chart.

What is it saying?

What features you used?

From this what you are showing us?

In [ ]:
# your code here
# If you want more cells, you can add or less cells you can remove, but dont change the structure.

## Interpretation of your above chart

Explain the Chart.

What is it saying?

What features you used?

From this what you are showing us?

## Stage 4 – Documentation, Insights and Presentation

Show a dashboard aligning all the charts in powerbi by connecting python in PowerBI

Summarize findings in plain English (what do the patterns mean)

Highlight 3–5 key insights (trends, anomalies, correlations)

Provide recommendations for business or decision-making

Explain the FINAL STORY WITH THE DASHBOARD

Create a PDF pasting your DASHBOARD, explaining all the above mentioned concepts and submit it

In [ ]:
# your stage 4 pdf Link

'''
step1 --> Create a docs that should have all the above mentioned
step2 --> Save it as "Stage4_doc"
Step3 --> Download it as PDF
step4 --> Upload the pdf in your drive
step5 --> Right click on your pdf in drive
step6 --> click share and change access into anyone with the link (Viewer)
step7 --> click copy link and paste it here...
You are done.
'''

'\nstep1 --> Create a docs that should have all the above mentioned\nstep2 --> Save it as "Stage4_doc"\nStep3 --> Download it as PDF\nstep4 --> Upload the pdf in your drive\nstep5 --> Right click on your pdf in drive\nstep6 --> click share and change access into anyone with the link (Viewer)\nstep7 --> click copy link and paste it here...\nYou are done.\n'